project:
  name: quickstart-boomi-eks-molecule
  owner: quickstart-eng@amazon.com
  regions:
  - eu-north-1
  - me-south-1
  - us-east-1
  - us-east-2
  - us-west-2
  template: templates/boomi-eks-master.template.yaml
  parameters:
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
tests:
  defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ProvisionBastionHost: Disabled
      EKSPublicAccessEndpoint: Enabled
  public-endpoint:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Disabled
      ProvisionBastionHost: Enabled
    regions:
      - ap-northeast-2
  cluster-autoscaler:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Enabled
      ProvisionBastionHost: Enabled
      EKSPublicAccessEndpoint: Disabled
    regions:
    - eu-central-1
  efs:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EfsStorageClass: Enabled
      ClusterAutoScaler: Disabled
      ManagedNodeGroup: 'yes'
      ManagedNodeGroupAMIType: AL2_x86_64
      EKSPublicAccessEndpoint: Disabled
      ProvisionBastionHost: Enabled
    regions:
    - us-west-2
  efs-prov:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EfsStorageClass: Enabled
      ClusterAutoScaler: Disabled
      EfsThroughputMode: provisioned
      EfsProvisionedThroughputInMibps: 100
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
    regions:
    - ap-east-1
  managed-node-group:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Disabled
      ManagedNodeGroup: 'yes'
      ManagedNodeGroupAMIType: AL2_x86_64
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
    regions:
    - ap-south-1
  monitoring-prom-graf:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      MonitoringStack: Prometheus + Grafana
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
    regions:
    - ap-southeast-2
    - us-west-2
  2az:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: "2"
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
    regions:
    - ca-central-1
    - cn-north-1
    - cn-northwest-1
  no-logging:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: "2"
      EKSClusterLoggingTypes: ""
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
    regions:
    - eu-west-1
  with-hybrid:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Disabled
      ManagedNodeGroup: 'yes'
      ManagedNodeGroupAMIType: AL2_x86_64
      MangedNodeGroupLabel: TestMNG
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
    regions:
    - us-west-2
  alb-ingress:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ALBIngressController: Enabled
      EKSPublicAccessEndpoint: Disabled
      ProvisionBastionHost: Enabled
    regions:
    - us-east-2

  enable-oidc:
    regions:
      - eu-west-2
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      IamOidcProvider: Enabled
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled

  managed-node-group-ASC:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Enabled
      ManagedNodeGroup: 'yes'
      ManagedNodeGroupAMIType: AL2_x86_64
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Enabled
    regions:
    - ap-south-1
