apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: molecule-ingress
  annotations:
    # trigger the alb-ingress-controller
    kubernetes.io/ingress.class: alb
    # set ALB parameters
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: !Ref CertificateArn
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
    # allow 404s on the health check
    alb.ingress.kubernetes.io/healthcheck-path: "/_admin/status"
    alb.ingress.kubernetes.io/success-codes: "200,404"
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: molecule-service
              servicePort: 443
